# Generated by Django 3.2.16 on 2023-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis_details',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', max_length=250)),
                ('description', models.CharField(default='NA', max_length=250)),
                ('email', models.CharField(default='NA', max_length=250)),
                ('mutation_database', models.CharField(default='NA', max_length=250)),
                ('consensus_percentage', models.IntegerField(default=20)),
                ('target_coverage', models.IntegerField(default=10000)),
                ('length_cutoff', models.IntegerField(default=100)),
                ('score_cutoff', models.IntegerField(default=30)),
                ('error_rate', models.IntegerField(default=0)),
                ('min_var_qual', models.IntegerField(default=0)),
                ('min_read_depth', models.IntegerField(default=0)),
                ('min_allele_count', models.IntegerField(default=0)),
                ('min_mutation_freq', models.IntegerField(default=0)),
            ],
        ),
    ]
