# Generated by Django 3.2.16 on 2023-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis_details',
            old_name='consensus_percentage',
            new_name='consensusPercentage',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='error_rate',
            new_name='errorRate',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='length_cutoff',
            new_name='lengthCutoff',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='min_allele_count',
            new_name='minimumAlleleCount',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='min_mutation_freq',
            new_name='minimumMutationFrequency',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='min_read_depth',
            new_name='minimumReadDepth',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='min_var_qual',
            new_name='minimumVariantQuality',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='score_cutoff',
            new_name='scoreCutoff',
        ),
        migrations.RenameField(
            model_name='analysis_details',
            old_name='target_coverage',
            new_name='targetCoverage',
        ),
        migrations.RemoveField(
            model_name='analysis_details',
            name='mutation_database',
        ),
        migrations.RemoveField(
            model_name='analysis_details',
            name='name',
        ),
        migrations.AddField(
            model_name='analysis_details',
            name='ProjectID',
            field=models.CharField(default='PRJN00923', max_length=250),
        ),
        migrations.AddField(
            model_name='analysis_details',
            name='mutationDatabase',
            field=models.CharField(default='Stanford Mutation Database', max_length=250),
        ),
        migrations.AlterField(
            model_name='analysis_details',
            name='description',
            field=models.CharField(default='DTG virological failure adults in Uganda', max_length=250),
        ),
        migrations.AlterField(
            model_name='analysis_details',
            name='email',
            field=models.CharField(default='member@hivseqdb.org', max_length=250),
        ),
    ]
