# Generated by Django 3.2.16 on 2023-01-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20230112_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('analysis_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_ID', models.CharField(default='S001', max_length=250)),
                ('gene', models.CharField(default='IN', max_length=250)),
                ('wildType', models.CharField(default='N', max_length=250)),
                ('position', models.IntegerField(default=100)),
                ('mutation', models.CharField(default='H', max_length=250)),
                ('mutation_Frequency', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('Consensus_sequence', models.CharField(default='ACGTGGGGGGGTCTGGGG', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NewAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_ID', models.CharField(default='PRJN00923', max_length=250)),
                ('description', models.CharField(default='DTG virological failure adults in Uganda', max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mutation_Database', models.CharField(max_length=250)),
                ('consensus_Percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('target_Coverage', models.DecimalField(decimal_places=2, default=10000, max_digits=5)),
                ('length_Cutoff', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('score_Cutoff', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('error_Rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_Variant_Quality', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('minimum_Read_Depth', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('minimum_Allele_Count', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('minimum_Mutation_Frequency', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='analysis_details',
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='project_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.newanalysis'),
        ),
    ]
