# Generated by Django 3.2.16 on 2023-01-13 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='samplingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
