# Generated by Django 3.2.16 on 2023-01-13 11:35

from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGS',
            fields=[
                ('sampleID', models.AutoField(primary_key=True, serialize=False)),
                ('sampleName', models.CharField(max_length=50)),
                ('fastqFile', models.FileField(blank=True, null=True, upload_to=uploads.models.project_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('RegionSequenced', models.CharField(max_length=50)),
                ('SequencingTechnology', models.CharField(max_length=50)),
                ('SequencingPlatform', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFastq',
        ),
        migrations.AddField(
            model_name='ngs',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.project'),
        ),
    ]
