# Generated by Django 3.2.16 on 2023-01-13 12:44

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20230113_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastq_File', models.FileField(blank=True, null=True, upload_to=uploads.models.project_upload_path)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='RegionSequenced',
            new_name='Region_Sequenced',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='SequencingPlatform',
            new_name='Sequencing_Platform',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='SequencingTechnology',
            new_name='Sequencing_Technology',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectID',
            new_name='project_ID',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectName',
            new_name='project_Name',
        ),
        migrations.AddField(
            model_name='project',
            name='fastq_File',
            field=models.FileField(blank=True, null=True, upload_to=uploads.models.project_upload_path),
        ),
        migrations.DeleteModel(
            name='NGS',
        ),
    ]
