# Generated by Django 3.2.16 on 2023-01-13 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20230113_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_File', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='project',
            name='Sequencing_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='Sequencing_Technology',
            field=models.CharField(choices=[('miseq', 'Illumina MiSeq'), ('nextseq', 'Illumina NextSeq'), ('novaseq', 'Illumina NovaSeq')], max_length=50),
        ),
    ]
