# Generated by Django 3.2.16 on 2023-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20230113_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Sequencing_Technology',
            field=models.CharField(max_length=50),
        ),
    ]
